name: Generate Keystore

on:
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore release-key.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias bokharest-key \
            -storepass "AA102030aa" \
            -keypass "AA102030aa" \
            -dname "CN=Bokharest, OU=Dev, O=Bokharest, L=Cairo, S=Cairo, C=EG"

      - name: Convert to Base64
        run: base64 -i release-key.jks -w 0 > release-key-base64.txt

      - name: Upload Keystore Files
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            release-key.jks
            release-key-base64.txt
